name: geoexploxer
services:
  - name: backend
    source_dir: /backend
    github:
      repo: ston6919/geoexploxer
      branch: main
    run_command: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "core.settings_production"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        generate_value: true
    health_check:
      http_path: /api/hello/

  - name: frontend
    source_dir: /frontend
    github:
      repo: ston6919/geoexploxer
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${backend.URL}
    routes:
      - path: /
    health_check:
      http_path: /

databases:
  - name: db
    engine: PG
    version: "15"
    production: false
