# Generated by Django 4.2.23 on 2025-08-15 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance & Banking'), ('retail', 'Retail & E-commerce'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('real_estate', 'Real Estate'), ('food_beverage', 'Food & Beverage'), ('entertainment', 'Entertainment & Media'), ('automotive', 'Automotive'), ('fashion', 'Fashion & Beauty'), ('travel', 'Travel & Tourism'), ('other', 'Other')], max_length=50)),
                ('business_description', models.TextField()),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('business_size', models.CharField(choices=[('startup', 'Startup (1-10 employees)'), ('small', 'Small Business (11-50 employees)'), ('medium', 'Medium Business (51-200 employees)'), ('large', 'Large Business (200+ employees)'), ('enterprise', 'Enterprise (1000+ employees)')], max_length=20)),
                ('target_market', models.TextField(help_text='Describe your ideal customers')),
                ('target_demographics', models.TextField(help_text='Age, gender, income level, etc.')),
                ('geographic_markets', models.TextField(help_text='Where do you operate/sell?')),
                ('products_services', models.TextField(help_text='What products or services do you offer?')),
                ('unique_value_proposition', models.TextField(help_text='What makes you different?')),
                ('pricing_strategy', models.TextField(help_text='How do you price your offerings?')),
                ('main_competitors', models.TextField(help_text='Who are your main competitors?')),
                ('competitive_advantages', models.TextField(help_text='What advantages do you have?')),
                ('business_goals', models.TextField(help_text='What are your main business objectives?')),
                ('current_challenges', models.TextField(help_text='What challenges are you facing?')),
                ('current_marketing', models.TextField(help_text='What marketing channels do you use?')),
                ('brand_values', models.TextField(help_text='What are your core brand values?')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
