# Generated by Django 4.2.23 on 2025-08-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_aimodel_searchterm_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='cost_per_million_input_usd',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cost per million input tokens in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='cost_per_million_output_usd',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cost per million output tokens in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='current_cost_input_usd',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current cost for input tokens in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='current_cost_output_usd',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current cost for output tokens in USD', max_digits=10, null=True),
        ),
    ]
