# Generated by Django 4.2.23 on 2025-08-16 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_aimodel_cost_per_million_input_usd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchlog',
            name='business_mentioned',
        ),
        migrations.RemoveField(
            model_name='searchlog',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='searchlog',
            name='mention_context',
        ),
        migrations.RemoveField(
            model_name='searchlog',
            name='sentiment',
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_mentioned', models.BooleanField(default=False, help_text='Whether the business was mentioned in the response')),
                ('mention_context', models.TextField(blank=True, help_text='Context around the business mention')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], help_text='Sentiment of the mention', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence in sentiment analysis (0-1)', max_digits=3, null=True)),
                ('analysis_model', models.CharField(help_text='Model used for analysis (e.g., google/gemma-2-9b-it)', max_length=100)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('analysis_duration_ms', models.IntegerField(blank=True, help_text='Time taken for analysis in milliseconds', null=True)),
                ('raw_analysis_response', models.TextField(blank=True, help_text='Raw response from the analysis model')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='users.businessprofile')),
                ('search_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='users.searchlog')),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'ordering': ['-analysis_timestamp'],
            },
        ),
    ]
